title: 'Machine Learning and Fluid Dynamics'
author: Henning Hermerschmidt
copyright: "2021"
logo: docs/vanGogh_StarryNight_wikipedia.jpg

html:
  home_page_in_navbar: false

bibtex_bibfiles: ../../literature/MachineLearning.bib